const KEY='sp_pro_v4';
const defaults={children:[],visits:[],growth:[],vaccines:[],appointments:[],settings:{clinic:'Mahamaya Clinic',doctor:'Dr Rajesh Sao',timing:'Mon–Sat 9:00 AM–8:00 PM • Sun 9:00 AM–2:00 PM',nextSession:''}};
let db=load(); let current='dashboard';
const navItems=[['CLINIC WORKSPACE'],['dashboard','⌂','Dashboard'],['children','👶','Children'],['visits','✨','Swarnaprashan Visits'],['growth','📈','Growth'],['vaccines','💉','Vaccination'],['appointments','🗓','Schedule'],['CARE & COMMUNICATION'],['education','📚','Parent Education'],['reports','🧾','Reports & Print'],['backup','💾','Backup & Restore'],['settings','⚙','Settings']];
function load(){try{return Object.assign({},defaults,JSON.parse(localStorage.getItem(KEY)||'{}'))}catch{return structuredClone(defaults)}}
function save(){localStorage.setItem(KEY,JSON.stringify(db));}
function uid(p='ID'){return p+Date.now().toString(36).toUpperCase().slice(-7)}
function esc(s=''){return String(s).replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}
function toast(t){let x=document.querySelector('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)}
function age(d){if(!d)return '—';let b=new Date(d),n=new Date(),m=(n-b)/(365.25*864e5);return m<2?Math.max(0,Math.round(m*12))+' mo':Math.floor(m)+' y'}
function renderNav(){nav.innerHTML=navItems.map(x=>x.length===1?`<div class="nav-label">${x[0]}</div>`:`<button class="nav-item ${current===x[0]?'active':''}" data-nav="${x[0]}"><span>${x[1]}</span><span>${x[2]}</span></button>`).join('')}
function go(v){current=v;renderNav();render();sidebar.classList.remove('open')}
function dashboard(){let today=new Date().toISOString().slice(0,10);let upcoming=db.appointments.filter(a=>a.date>=today).sort((a,b)=>a.date.localeCompare(b.date)).slice(0,5);return `<div class="hero"><div><div class="eyebrow">Clinical child wellness registry</div><h2>Welcome, Super Admin</h2><p>Register once. Record every Swarnaprashan visit, safety screen, growth milestone and vaccination—then print or share professional records in seconds.</p><div class="hero-actions"><button class="primary" data-action="newChild">＋ New Child</button><button class="secondary" data-action="newVisit">＋ Record Visit</button><button class="secondary" data-nav="children">Find Child</button></div></div><div class="session-card"><div><small>Next Swarnaprashan Session</small><div class="big">${db.settings.nextSession||'Not configured'}</div><small>${esc(db.settings.timing)}</small></div><div><button class="secondary" data-nav="appointments">Schedule</button></div></div></div>
<div class="kpis"><div class="kpi"><div class="label">Registered Children</div><div class="value">${db.children.length}</div><div class="trend">Complete child registry</div></div><div class="kpi"><div class="label">Swarnaprashan Visits</div><div class="value">${db.visits.length}</div><div class="trend">Longitudinal records</div></div><div class="kpi"><div class="label">Upcoming</div><div class="value">${db.appointments.filter(a=>a.date>=today).length}</div><div class="trend">Scheduled follow-ups</div></div><div class="kpi"><div class="label">Growth Records</div><div class="value">${db.growth.length}</div><div class="trend">Height • Weight • BMI</div></div></div>
<div class="grid-2"><div class="panel"><div class="panel-head"><div><div class="eyebrow">Quick registry</div><h3>Recent Children</h3></div><button class="secondary" data-nav="children">View all</button></div>${db.children.length?`<div class="table-wrap"><table class="data-table"><thead><tr><th>ID</th><th>Child</th><th>Age</th><th>Mobile</th><th></th></tr></thead><tbody>${db.children.slice(-6).reverse().map(c=>`<tr><td>${c.id}</td><td><b>${esc(c.name)}</b><br><small class="muted">${esc(c.sex||'')}</small></td><td>${age(c.dob)}</td><td>${esc(c.mobile||'—')}</td><td><div class="mini-actions"><button data-print-child="${c.id}">🖨</button><button data-share-child="${c.id}">↗</button></div></td></tr>`).join('')}</tbody></table></div>`:`<div class="empty">No child registered yet. Use <b>New Child</b> to begin.</div>`}</div>
<div class="panel"><div class="panel-head"><div><div class="eyebrow">Today / next</div><h3>Clinic Worklist</h3></div></div><div class="worklist">${upcoming.length?upcoming.map(a=>`<div class="work-item"><div class="date-badge">${a.date.slice(5)}</div><div><b>${esc(childName(a.childId))}</b><div class="muted">${esc(a.purpose||'Swarnaprashan')}</div></div><span class="badge ok">Scheduled</span></div>`).join(''):`<div class="empty">No upcoming appointments.</div>`}</div></div></div>`}
function childName(id){return db.children.find(c=>c.id===id)?.name||'Unknown child'}
function listView(kind){let config={children:['Children','Child Registry','newChild',['ID','Child','Age','Guardian / Mobile']],visits:['Swarnaprashan Visits','Clinical administration records','newVisit',['Visit','Child','Date','Dose / Form']],growth:['Growth','Height • Weight • BMI tracking','newGrowth',['Record','Child','Date','Height / Weight']],vaccines:['Vaccination','Vaccination history & due status','newVaccine',['Record','Child','Vaccine','Date']],appointments:['Schedule','Appointments & Swarnaprashan calendar','newAppointment',['Appointment','Child','Date','Purpose']]}[kind];
let rows=(kind==='children'?db.children:db[kind]).map(r=>{if(kind==='children')return [r.id,`<b>${esc(r.name)}</b><br><small>${esc(r.sex||'')}</small>`,age(r.dob),`${esc(r.guardian||'')}<br><small>${esc(r.mobile||'')}</small>`];if(kind==='visits')return [r.id,childName(r.childId),r.date,`${esc(r.dose||'—')} • ${esc(r.form||'—')}`];if(kind==='growth')return [r.id,childName(r.childId),r.date,`${r.height||'—'} cm / ${r.weight||'—'} kg`];if(kind==='vaccines')return [r.id,childName(r.childId),esc(r.vaccine),r.date];return [r.id,childName(r.childId),r.date,esc(r.purpose||'')]}).reverse();
return `<div class="toolbar"><div><div class="eyebrow">${config[1]}</div><h2>${config[0]}</h2></div><button class="primary" data-action="${config[2]}">＋ Add ${kind==='children'?'Child':'Record'}</button></div><div class="panel">${rows.length?`<div class="table-wrap"><table class="data-table"><thead><tr>${config[3].map(x=>`<th>${x}</th>`).join('')}<th>Actions</th></tr></thead><tbody>${rows.map(r=>`<tr>${r.map(x=>`<td>${x}</td>`).join('')}<td><div class="mini-actions"><button data-action="printCurrent">🖨</button><button data-action="shareCurrent">↗</button></div></td></tr>`).join('')}</tbody></table></div>`:`<div class="empty">No records yet.</div>`}</div>`}
function education(){return `<div class="toolbar"><div><div class="eyebrow">Parent counselling library</div><h2>Parent Education</h2></div><button class="primary" data-action="shareEducation">Share Guidance</button></div><div class="grid-2"><div class="panel"><h3>Before Swarnaprashan</h3><p class="muted">Confirm child identity, current illness, allergy/ADR history, recent medication and parent consent. Defer and clinically assess when the child is acutely unwell.</p><span class="badge warn">Safety-first checklist</span></div><div class="panel"><h3>Home Follow-up</h3><p class="muted">Record any new symptom after administration, maintain routine nutrition, sleep and vaccination schedule, and contact the clinic if concerns arise.</p><span class="badge ok">Easy to share</span></div></div>`}
function reports(){return `<div class="toolbar"><div><div class="eyebrow">Professional documentation</div><h2>Reports & Print</h2></div></div><div class="grid-2"><div class="panel"><h3>Child Summary</h3><p class="muted">Select a child and generate a clean clinical summary containing demographics, Swarnaprashan visits, growth and vaccination records.</p><select class="select" id="reportChild"><option value="">Choose child…</option>${db.children.map(c=>`<option value="${c.id}">${esc(c.name)} • ${c.id}</option>`).join('')}</select><div class="hero-actions"><button class="primary" data-action="printChildSummary">🖨 Print / Save PDF</button><button class="secondary" data-action="shareChildSummary">↗ Share</button></div></div><div class="panel"><h3>Clinic Register</h3><p class="muted">Print a consolidated registry for documentation and audit.</p><div class="hero-actions"><button class="primary" data-action="printCurrent">Print Current View</button><button class="secondary" data-action="exportCSV">Export CSV</button></div></div></div>`}
function backup(){return `<div class="toolbar"><div><div class="eyebrow">Data safety</div><h2>Backup & Restore</h2></div></div><div class="grid-2"><div class="panel"><h3>Full JSON Backup</h3><p class="muted">Downloads children, visits, growth, vaccines, appointments and settings in one portable backup file.</p><button class="primary" data-action="exportBackup">⬇ Download Backup</button></div><div class="panel"><h3>Restore Backup</h3><p class="muted">Restore from a previously downloaded JSON backup. Existing app data will be replaced.</p><button class="secondary" data-action="importBackup">⬆ Choose Backup</button></div></div>`}
function settings(){return `<div class="toolbar"><div><div class="eyebrow">Clinic configuration</div><h2>Settings</h2></div></div><div class="panel"><div class="form-grid"><div class="field"><label>Clinic Name</label><input class="input" id="sClinic" value="${esc(db.settings.clinic)}"></div><div class="field"><label>Doctor</label><input class="input" id="sDoctor" value="${esc(db.settings.doctor)}"></div><div class="field full"><label>Clinic Timing</label><input class="input" id="sTiming" value="${esc(db.settings.timing)}"></div><div class="field"><label>Next Swarnaprashan Session</label><input class="input" type="date" id="sSession" value="${esc(db.settings.nextSession)}"></div></div><div class="hero-actions"><button class="primary" data-action="saveSettings">Save Settings</button></div></div>`}
function render(){view.innerHTML=current==='dashboard'?dashboard():['children','visits','growth','vaccines','appointments'].includes(current)?listView(current):current==='education'?education():current==='reports'?reports():current==='backup'?backup():settings()}
function modal(title,body,onSave){let m=document.createElement('div');m.className='modal';m.innerHTML=`<div class="modal-card"><div class="modal-head"><b>${title}</b><button class="close">×</button></div><div class="modal-body">${body}</div><div class="modal-foot"><button class="secondary closeBtn">Cancel</button><button class="primary saveBtn">Save</button></div></div>`;document.body.append(m);m.querySelector('.close').onclick=m.querySelector('.closeBtn').onclick=()=>m.remove();m.querySelector('.saveBtn').onclick=()=>{if(onSave(m)!==false)m.remove()}}
function childOptions(){return `<option value="">Choose child…</option>${db.children.map(c=>`<option value="${c.id}">${esc(c.name)} • ${c.id}</option>`).join('')}`}
function newChild(){modal('Register New Child',`<div class="section-title">Identity & Contact</div><div class="form-grid"><div class="field"><label>Child Name *</label><input class="input" name="name"></div><div class="field"><label>Date of Birth *</label><input class="input" type="date" name="dob"></div><div class="field"><label>Sex</label><select class="select" name="sex"><option>Male</option><option>Female</option><option>Other</option></select></div><div class="field"><label>Guardian Name</label><input class="input" name="guardian"></div><div class="field"><label>Mobile / WhatsApp</label><input class="input" name="mobile" inputmode="tel"></div><div class="field"><label>Blood Group</label><input class="input" name="blood"></div></div><div class="section-title">Clinical Background</div><div class="form-grid"><div class="field full"><label>Allergy / ADR</label><input class="input" name="allergy" placeholder="Drug / food allergy, prior reaction"></div><div class="field"><label>Birth Weight (kg)</label><input class="input" name="birthWeight" type="number" step="0.01"></div><div class="field"><label>Delivery</label><select class="select" name="delivery"><option>Normal vaginal</option><option>Caesarean</option><option>Assisted</option></select></div><div class="field full"><label>Medical / Development Notes</label><textarea class="textarea" name="notes" rows="3"></textarea></div></div>`,m=>{let f=Object.fromEntries([...m.querySelectorAll('[name]')].map(x=>[x.name,x.value]));if(!f.name||!f.dob){toast('Name and DOB are required');return false}db.children.push({...f,id:uid('CH-'),created:new Date().toISOString()});save();render();toast('Child registered successfully')})}
function newVisit(){if(!db.children.length){toast('Register a child first');return}modal('Record Swarnaprashan Visit',`<div class="section-title">Visit</div><div class="form-grid"><div class="field"><label>Child *</label><select class="select" name="childId">${childOptions()}</select></div><div class="field"><label>Date *</label><input class="input" type="date" name="date" value="${new Date().toISOString().slice(0,10)}"></div><div class="field"><label>Form</label><select class="select" name="form"><option>Classical preparation</option><option>Clinic preparation</option><option>Other</option></select></div><div class="field"><label>Dose</label><input class="input" name="dose" placeholder="e.g., drops / as advised"></div></div><div class="section-title">Pre-administration Safety Screen</div><div class="form-grid"><div class="field"><label>Current illness / fever</label><select class="select" name="ill"><option>No</option><option>Yes — clinically assessed</option></select></div><div class="field"><label>Known allergy / ADR</label><select class="select" name="adr"><option>No known</option><option>Present — reviewed</option></select></div><div class="field"><label>Recent medication</label><input class="input" name="meds"></div><div class="field"><label>Parent consent</label><select class="select" name="consent"><option>Obtained</option><option>Not obtained</option></select></div><div class="field full"><label>Clinical Notes / Advice</label><textarea class="textarea" name="notes" rows="4"></textarea></div></div>`,m=>{let f=Object.fromEntries([...m.querySelectorAll('[name]')].map(x=>[x.name,x.value]));if(!f.childId||!f.date){toast('Child and date required');return false}db.visits.push({...f,id:uid('SV-')});save();render();toast('Visit saved')})}
function newGrowth(){if(!db.children.length){toast('Register a child first');return}modal('Add Growth Record',`<div class="form-grid"><div class="field"><label>Child</label><select class="select" name="childId">${childOptions()}</select></div><div class="field"><label>Date</label><input class="input" type="date" name="date" value="${new Date().toISOString().slice(0,10)}"></div><div class="field"><label>Height (cm)</label><input class="input" type="number" step=".1" name="height"></div><div class="field"><label>Weight (kg)</label><input class="input" type="number" step=".1" name="weight"></div><div class="field full"><label>Notes</label><textarea class="textarea" name="notes"></textarea></div></div>`,m=>{let f=Object.fromEntries([...m.querySelectorAll('[name]')].map(x=>[x.name,x.value]));db.growth.push({...f,id:uid('GR-')});save();render();toast('Growth record saved')})}
function newVaccine(){if(!db.children.length){toast('Register a child first');return}modal('Add Vaccination Record',`<div class="form-grid"><div class="field"><label>Child</label><select class="select" name="childId">${childOptions()}</select></div><div class="field"><label>Vaccine</label><input class="input" name="vaccine"></div><div class="field"><label>Date</label><input class="input" type="date" name="date"></div><div class="field"><label>Status</label><select class="select" name="status"><option>Given</option><option>Due</option><option>Planned</option></select></div></div>`,m=>{let f=Object.fromEntries([...m.querySelectorAll('[name]')].map(x=>[x.name,x.value]));db.vaccines.push({...f,id:uid('VX-')});save();render();toast('Vaccination record saved')})}
function newAppointment(){if(!db.children.length){toast('Register a child first');return}modal('Schedule Appointment',`<div class="form-grid"><div class="field"><label>Child</label><select class="select" name="childId">${childOptions()}</select></div><div class="field"><label>Date</label><input class="input" type="date" name="date"></div><div class="field"><label>Time</label><input class="input" type="time" name="time"></div><div class="field"><label>Purpose</label><input class="input" name="purpose" value="Swarnaprashan"></div></div>`,m=>{let f=Object.fromEntries([...m.querySelectorAll('[name]')].map(x=>[x.name,x.value]));db.appointments.push({...f,id:uid('AP-')});save();render();toast('Appointment scheduled')})}
function download(name,text,type='application/json'){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
function exportBackup(){download(`swarnaprashan-backup-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(db,null,2))}
function exportCSV(){let rows=[['ID','Name','DOB','Sex','Guardian','Mobile'],...db.children.map(c=>[c.id,c.name,c.dob,c.sex,c.guardian,c.mobile])];download('swarnaprashan-child-registry.csv',rows.map(r=>r.map(v=>'"'+String(v||'').replaceAll('"','""')+'"').join(',')).join('\n'),'text/csv')}
function childSummary(id){let c=db.children.find(x=>x.id===id);if(!c)return '';let vs=db.visits.filter(x=>x.childId===id),gs=db.growth.filter(x=>x.childId===id),vxs=db.vaccines.filter(x=>x.childId===id);return `SWARNAPRASHAN @ ${db.settings.clinic}\nChild: ${c.name} (${c.id})\nDOB: ${c.dob} | Age: ${age(c.dob)} | Sex: ${c.sex||'—'}\nGuardian: ${c.guardian||'—'} | Mobile: ${c.mobile||'—'}\nAllergy/ADR: ${c.allergy||'None recorded'}\n\nSwarnaprashan Visits: ${vs.length}\n${vs.map(v=>`${v.date}: ${v.form||''} ${v.dose||''}`).join('\n')}\n\nGrowth Records: ${gs.length}\n${gs.map(g=>`${g.date}: ${g.height||'—'} cm, ${g.weight||'—'} kg`).join('\n')}\n\nVaccination Records: ${vxs.length}\n${vxs.map(v=>`${v.date||'—'}: ${v.vaccine||''} (${v.status||''})`).join('\n')}\n\n${db.settings.doctor}\n${db.settings.timing}`}
function shareText(text){if(navigator.share)navigator.share({title:'Swarnaprashan @ Mahamaya Clinic',text}).catch(()=>{});else navigator.clipboard?.writeText(text).then(()=>toast('Copied for sharing'))}
function printChild(id){let text=childSummary(id);let w=open('','_blank');w.document.write(`<html><head><title>Child Summary</title><style>body{font-family:Arial;padding:32px;color:#173d33}pre{white-space:pre-wrap;font:15px Arial;line-height:1.6}h2{border-bottom:2px solid #c8a34f;padding-bottom:10px}</style></head><body><h2>Swarnaprashan @ Mahamaya Clinic</h2><pre>${esc(text)}</pre></body></html>`);w.document.close();w.print()}
function searchGlobal(){let q=globalSearch.value.trim().toLowerCase();if(!q)return;let hits=db.children.filter(c=>[c.name,c.mobile,c.id,c.guardian].some(v=>String(v||'').toLowerCase().includes(q)));go('children');setTimeout(()=>toast(hits.length?`${hits.length} matching child record(s)`:'No matching child found'),0)}
document.addEventListener('click',e=>{let n=e.target.closest('[data-nav]');if(n)return go(n.dataset.nav);let a=e.target.closest('[data-action]');if(a){let fn={newChild,newVisit,newGrowth,newVaccine,newAppointment,exportBackup,importBackup:()=>restoreInput.click(),exportCSV,printCurrent:()=>print(),shareCurrent:()=>shareText(`Swarnaprashan @ ${db.settings.clinic} — ${current} view`),shareEducation:()=>shareText('Swarnaprashan parent guidance: clinical screening, parent consent, routine nutrition, sleep, vaccination follow-up and prompt clinic contact for concerns.'),saveSettings:()=>{db.settings={clinic:sClinic.value,doctor:sDoctor.value,timing:sTiming.value,nextSession:sSession.value};save();render();toast('Settings saved')},printChildSummary:()=>{let id=document.querySelector('#reportChild')?.value;if(id)printChild(id);else toast('Choose a child')},shareChildSummary:()=>{let id=document.querySelector('#reportChild')?.value;if(id)shareText(childSummary(id));else toast('Choose a child')}}[a.dataset.action];fn?.();return}let p=e.target.closest('[data-print-child]');if(p)return printChild(p.dataset.printChild);let s=e.target.closest('[data-share-child]');if(s)return shareText(childSummary(s.dataset.shareChild))});
menuBtn.onclick=()=>sidebar.classList.toggle('open');searchBtn.onclick=searchGlobal;globalSearch.addEventListener('keydown',e=>{if(e.key==='Enter')searchGlobal()});restoreInput.onchange=async()=>{let f=restoreInput.files[0];if(!f)return;try{let x=JSON.parse(await f.text());db=Object.assign({},defaults,x);save();render();toast('Backup restored')}catch{toast('Invalid backup file')}};
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});renderNav();render();
